### ISSUE TITLE
Improve stream playback page

### ISSUE THREAD

**Issue by fkaa** [fkaa/streamhead#17]
Currently it has a bunch of unimplemented and missing functionality:

* Fullscreen
* A proper volume slider

Another question is if we keep the "buffer slider". I don't feel it's really that useful and mostly just confuses people. That leaves us with a play/pause button, volume slider, and maybe some options regarding buffer/latency.

**Comment by Jokler** [comment]
Maybe the buffer slider could be hidden behind some "advanced buffer settings" checkbox in the settings.

**Comment by fkaa** [comment]
The page has been "improved" in that it's just a `<video>` tag now.
